---
- name: Prepare the Molecule Test Resources
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - iptables
          - openssh-server
          - curl
          - iputils-ping
        state: latest
        update_cache: yes

- name: Prepare hostB
  hosts: hostB
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install postgresql-client
      apt:
        name:
          - postgresql-client
        state: latest
